### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by karankashyap** [taromero/swal-forms#22] opened 2016-08-02 10:16 UTC
SweetAlert is working fine. Swal forms is not. 
**swal-forms.js** (src https://github.com/taromero/swal-forms/blob/master/swal-forms.js) and is initialized after swal.js

**Console error:** 
Uncaught TypeError: _Cannot read property 'querySelector' of null at_ swal-forms.js:109 
_insertFormInSwalModal @_ swal-forms.js:109
_swal.withForm @_ swal-forms.js:15

**swal-forms.js:109**
`var buttonContainerTag = sweetAlertModal.querySelector('.sa-button-container') || sweetAlertModal.querySelector('.cancel')`

I'm using Complex example (src https://cdn.rawgit.com/taromero/swal-forms/master/live-demo/live-demo.html)

**Comment by taromero** [comment] 2016-08-20 14:27
1- Are you running swal-forms after the window.onload event?
2- Have you added a div with the sweet-alert class?

It seems that the script is failing to find the sweet alert modal, which could be caused by either of those.

If you have a div with the sweet-alert class, and you are calling sweet-forms after window.onload, please provide a JsFiddle or so to reproduce the error.

**Comment by taromero** [comment] 2016-11-19 14:27
Closing this ticket since no feedback was provided.

**Closed as completed by taromero** 2016-11-19 14:27 UTC
